#!/usr/bin/env bash
# rclone dedupe skip $1 -vP
# rclone dedupe skip $2 -vP
# Generally dedupe is not required. But if you get a 'parent' or other error, try running dedupe on source and destination

echo STARTING DIFFMOVE;echo
rclone check $1 $2 --size-only --one-way --fast-list > check.log 2>&1
awk 'BEGIN { FS = ": " } /ERROR/ {print $2}' check.log > difflist.txt
echo Number of files to be moved
num_files=`cat difflist.txt | wc -l`
echo $num_files
[ $num_files -gt 0 ] && {
echo STARTING RCLONE MOVE from $1 to $2;echo
rclone move --files-from difflist.txt $1 $2 -vP --stats=10s --drive-use-trash=false --drive-server-side-across-configs=true \
  --transfers 16 --checkers=16 --use-mmap  --max-backlog=2000000 --fast-list --tpslimit 4 --tpslimit-burst 20
rm check.log difflist.txt; }
echo DIFFMOVE FINISHED moving differential files from $1 to $2;echo
