#!/usr/bin/env bash
echo STARTING DIFFSETS ; echo
SET_DIR=/opt/diffmove/sets

process_sets () {
  for set_file in $@; do
    echo set file = $set_file ; sleep 3s
    column -t $SET_DIR/$set_file|tee /dev/tty|sed '/^\s*#.*$/d'|\
    while IFS=$' \t\n' read -r src dest; do
      echo Running /opt/diffmove/diffmove $src $dest
      /opt/diffmove/diffmove $src $dest
    done
  done
}

process_sets $@

echo ; echo DIFFSETS COMPLETED ; echo