#!/usr/bin/env bash
# rclone dedupe skip $1 -vP
# rclone dedupe skip $2 -vP
# Generally dedupe is not required. But if you get a 'parent' or other error, try running dedupe on source and destination

echo STARTING DIFFMOVE;echo
rclone check $1 $2 --size-only --one-way > check.log 2>&1
awk 'BEGIN { FS = ": " } /ERROR/ {print $2}' check.log > difflist.txt
echo Number of files to be moved;cat difflist.txt | wc -l
echo STARTING RCLONE MOVE;echo
rclone move --files-from difflist.txt $1 $2 -vP --drive-server-side-across-configs=true --transfers 30
rm check.log difflist.txt
echo DIFFMOVE FINISHED;echo
