#!/usr/bin/env bash
# Requires installation of moreutils to run combine.
# sudo apt install moreutils


rclone tree -di --level 2 $1>tmp1
rclone tree -di --level 2 $2>tmp2

sort -o tmp1 tmp1
sort -o tmp2 tmp2

combine tmp1 not tmp2>not_in_2
combine tmp2 not tmp1>not_in_1

rm tmp1
rm tmp2
