#!/usr/bin/env bash

SADIR=/opt/sa/
MINSA=1
MAXSA=1000
COUNT=$MINSA

action=$1
src=$2
dest=$3

while read -r name; do
    echo rclone $action "$src$name" "$dest$name" --drive-service-account-file=$COUNT.json \
    --drive-stop-on-upload-limit -vP
    COUNT=$(( $COUNT%$MAXSA+1 ))
done < <(rclone tree -d -i --level 1 --full-path --noreport $src | tail -n +2)
