#!/usr/bin/env bash
# USAGE ./rc_one sync src: dest:  <= change sync to copy/move as needed

action=$1
src=$2
dest=$3

while read -r name; do
    echo rclone $action "$src$name" "$dest$name" -vP
    COUNT=$(( $COUNT%$MAXSA+1 ))
done < <(rclone tree -d -i --level 1 --full-path --noreport $src | tail -n +2)
