#!/usr/bin/env bash
# USAGE ./rc_one sync src: dest:  <= change sync to copy/move as needed

action=$1
src=$2
dest=$3

while read -r name; do
    rclone $action "$src$name" "$dest$name" -vP
done < <(rclone tree -d -i --level 1 --full-path --noreport $src | sort -r)
